#!/usr/bin/python3

import os
import re
import sys
import pprint

BASEDIR = os.path.dirname(os.path.abspath(sys.argv[0]))

print("""// -*- c -*-
// AUTOMATICALLY GENERATED BY {}, DO NOT EDIT.

""".format(sys.argv[0]))

with open(os.path.join(BASEDIR, "..", "output.c")) as f:
    t = f.read()
    patterns = re.findall('case (\d+):\n\s*report_pstr\(PSTR\("(.+?)"\)\);', t, re.MULTILINE)

if not patterns:
    print("output.c: error: no string compression patterns found. (update the regular expression?)")
    sys.exit(1)

print("/*\n\nPatterns gleaned from output.c:\n")
pprint.pprint(patterns)
print("\n*/\n\n")

with open(os.path.join(BASEDIR, "..", "strings.h.in")) as f:
    for line in f:
        m = re.match('^(\s*#\s*define\s+\S+\s+)"(.+?)"(\s*(?://.*)?)$', line.rstrip())
        #m = re.match('^\s*#\s*define', line.rstrip())
        if m:
            define, string, comment = m.groups()
            for code, pattern in patterns:
                string = string.replace(pattern, "\\" + oct(int(code))[2:])
            print('{}"{}"{}'.format(define, string, comment))
            continue
        print(line.rstrip('\n'))

# End of file.
