#!/bin/bash

if [ "$FORCECOL" != "" ] || tty </dev/stdout >/dev/null; then
    sed \
	-e 's/\(\[ok\].*\)$/[0;1;32m\1[0m/' \
	-e 's/\(\[fail\].*\)$/[0;1;31m\1[0m/' \
	-e 's/\(\[start\].*\)$/[0;1m\1[0m/' \
	-e 's/\(\[report\].*\)$/[0;1;35m\1[0m/'
else
    cat
fi

# End of file.
